version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: Jira Example
    path: ""
    text-resources:
      - path: src/*.html
        format: react-hardcoded
