version: "0.1"

environments:
  - name: master
    branch: master
    mode: pull-request
    
    
apps:
  - name: jira_clone
    path: client/
    text-resources:
      - path: "*.tsx"
        format: react-hardcoded
        
        
        
        
        
        
